[package]
name = "simple_raymarcher"
version = "0.1.0"
authors = ["LokiVKlokeNaAndoke <ma.ba1@rambler.ru>"]
edition = "2018"

[profile.dev]
opt-level = 1

[dependencies]
ggez = "0.5.0-rc.2"
arr_macro = "0.1.2"
num = "0.2.0"